//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanbanMVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class subcardlist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subcardlist()
        {
            this.cards = new HashSet<cards>();
        }
    
        public decimal Id { get; set; }
        public string name { get; set; }
        public decimal cardlistId { get; set; }
        public bool isExpanded { get; set; }
        public int order { get; set; }
        public string created_at { get; set; }
    
        public virtual cardlist cardlist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cards> cards { get; set; }
    }
}
